"""
explain.py
-----------
Builds the human-readable "why this candidate ranked where they did"
explanation. Every sentence is assembled from the agents' own evidence
strings — nothing here is freely generated by an LLM, which is exactly
how the system avoids hallucinated or unsupported justifications.
"""


def build_explanation(name: str, agent_results: dict, combined: dict) -> str:
    parts = [
        f"Overall score {combined['final_score']}/100 "
        f"(confidence {combined['confidence']}%, risk: {combined['risk_level']}).",
        f"Skills ({combined['skill_score']}/100): {agent_results['skill']['evidence']}.",
        f"Experience ({combined['experience_score']}/100): {agent_results['experience']['evidence']}.",
        f"Growth ({combined['growth_score']}/100): {agent_results['growth']['evidence']}.",
        f"Behaviour ({combined['behaviour_score']}/100): {agent_results['behaviour']['evidence']}.",
        f"Trust & Risk: {agent_results['trust_risk']['evidence']}.",
    ]
    return " ".join(parts)
